# Generated by Django 2.1.7 on 2019-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='comentarios',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
