# Generated by Django 2.1.7 on 2019-04-15 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=2)),
                ('monto', models.IntegerField()),
            ],
            options={
                'ordering': ['presupuesto'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.IntegerField()),
            ],
            options={
                'ordering': ['fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('run', models.CharField(help_text='Sin puntos ni guión', max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('cf', 'Femenino'), ('cm', 'Masculino'), ('tf', 'Transfemenino'), ('tm', 'Transmasculino'), ('nb', 'No binario'), ('nd', 'No declara')], max_length=2)),
                ('fecha_nacimiento', models.DateField(help_text='e.g. 31/12/1990', verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Número debe ser ingresado en formato '+569XXXXXXXX'.", regex='^\\+?569?\\d{8}$')], verbose_name='Número de teléfono celular')),
                ('correo', models.EmailField(blank=True, max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('monto_default', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Prestaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ManyToManyField(through='reg.Cotizado', to='reg.Prestacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Paciente')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg.Paciente'),
        ),
        migrations.AddField(
            model_name='cotizado',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Prestacion'),
        ),
        migrations.AddField(
            model_name='cotizado',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Presupuesto'),
        ),
    ]
