# Generated by Django 2.1.7 on 2019-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
